##
##https://www.youtube.com/watch?v=QGG_76OmRnA&t=350s
##
version: "3"

services:

  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - ./node-red-data:/data

  mosquitto:
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto-data/config/:/mosquitto/config/
      - ./mosquitto-data/log/:/mosquitto/log/
      - ./mosquitto-data/data:/mosquitto/data/
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - node-red-net

volumes:
  node-red-data:
  mosquitto-data:
  
networks:
  node-red-net:
